apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: demopipeline
description: demopipeline application 
serialPipeline:
 stages:
 - targetId: staging
 - targetId: prod
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: staging
description: staging cluster
gke:
 cluster: projects/chrome-sum-415007/locations/us-central1/clusters/demopipelinestg
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: prod
description: prod cluster
requireApproval: true
gke:
 cluster: projects/chrome-sum-415007/locations/us-central1-a/clusters/demopipelineprod
