apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: new-cicd-demo-app
description: cicd-demo application 
serialPipeline:
 stages:
 - targetId: staging
 - targetId: prod
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: staging
description: staging cluster
gke:
 cluster: projects/black-display-408016/locations/us-central1-c/clusters/stage-gke
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: prod
description: prod cluster
requireApproval: true
gke:
 cluster: projects/black-display-408016/locations/us-central1-c/clusters/prod-gke
