apiVersion: apps/v1
kind: Deployment
metadata:
  name: demopipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demopipeline
  template:
    metadata:
      labels:
        app: demopipeline
    spec:
      containers:
        - name: demopipeline
          image: sample-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demopipeline
spec:
  type: LoadBalancer
  selector:
    app: demopipeline
  ports:
    - port: 80
      targetPort: 80